export const palabras = [
  'abeto', 'actor', 'aguas', 'agudo', 'alado', 'albas', 'altar', 'Anton', 'atizo', 'avala', 'avion', 'azul',
  'babas', 'bacas', 'bache', 'bajes', 'balas', 'bebes', 'belen', 'Berto', 'bicho', 'bizco', 'bueno', 'busca',
  'cabra', 'cafes', 'cajas', 'calar', 'calas', 'calca', 'calla', 'calma', 'camba', 'campo', 'canas', 'cantos', 'capto', 'caras',
  'carlo', 'carro', 'casas', 'catar', 'caida', 'cejas', 'Celia', 'cenas', 'cepas', 'cerca', 'cerco', 'cerdo', 'chile', 'china',
  'ciego', 'cines', 'citas', 'clara', 'clavo', 'colas', 'colon', 'colon', 'coral', 'coras', 'corea', 'corro', 'cosas', 'costo',
  'crudo', 'curar', 'dados', 'dagas', 'datos', 'danos', 'dejar', 'dejes', 'denso', 'dices', 'divos', 'dotes', 'dunas', 'dures',
  'duros', 'ellos', 'echas', 'edito', 'elevo', 'emule', 'emulo', 'enoje', 'error', 'estas', 'fallo', 'falto', 'feria', 'fetos',
  'fijos', 'filas', 'filia', 'finca', 'gafas', 'galas', 'Gales', 'galos', 'ganas', 'ganes', 'gases', 'gasto', 'giras', 'gordo',
  'gorro', 'grave', 'grito', 'hacer', 'halos', 'hasta', 'heces', 'hielo', 'ideas', 'india', 'inflo', 'islas', 'japon', 'jefas',
  'jerga', 'Josue', 'julio', 'malos', 'mania', 'marca', 'marco', 'marti', 'maria', 'mario', 'matar', 'melon', 'menos', 'meter', 'metro', 'moler',
  'monte', 'morir', 'nacer', 'nadar', 'narro', 'natas', 'naves', 'necio', 'ninos', 'notas', 'nubes', 'obras', 'ocios', 'ollas',
  'ondas', 'onzas', 'opera', 'otros', 'ovulo', 'oirte', 'palas', 'paris', 'pedir', 'pelea', 'pelos', 'peras', 'perro', 'pesos',
  'pilas', 'pinto', 'poder', 'pollo', 'quedo', 'quema', 'quito', 'reloj', 'rubio', 'rasco', 'ratas', 'ratos', 'redes', 'remar',
  'renos', 'renta', 'sabio', 'sacar', 'salir', 'selva', 'sanar', 'sopas', 'secar', 'serio', 'situo', 'sobar', 'sonar', 'subir',
  'sucio', 'siete', 'tabla', 'tacos', 'Tania', 'tapas', 'tazas', 'telon', 'tener', 'tenis', 'terco', 'terso', 'Texas', 'tipos',
  'tiras', 'todas', 'todos', 'tomar', 'Tomas', 'tonos', 'tonto', 'toque', 'torpe', 'trote', 'vacas', 'vagos', 'valer', 'valor',
  'veces', 'vedas', 'velas', 'vemos', 'venas', 'venir', 'verde', 'viera', 'vigas', 'vinos', 'vivir', 'volar', 'votar', 'yates',
  'yemas', 'yemen', 'yendo', 'yenes', 'yesca', 'yogur', 'yugos', 'zonas', 'zorro', 'zurdo', 'zurra', 'zurri', 'zurro', 'zurza', 'zurzo', 'zurce',
  "palma", "palos", "palpa", "panes", "papua", "papus", "paras", "parda", "pardo", "paree", "paren", "pares",
  "paree", "parta", "parti", "paras", "paria", "paris", "pasas", "pasen", "pases", "paseo", "pasas", "pases",
  "patas", "patea", "patos", "pause", "pavos", "pecas", "peces", "pecio", "pedes", "pegas", "pegue", "peina",
  "pelis", "pelos", "penan", "penas", "penda", "pende", "penen", "penes", "pensa", "pense", "penas", "penes",
  "peras", "perdi", "peros", "pesad", "pesas", "pesca", "pesen", "peses", "pesos", "petas", "petos", "petro",
  "pican", "picas", "picha", "picos", "pidas", "pides", "pifie", "pines", "pipas", "pisad", "pisco", "pises",
  "pitan", "pitos", "piura", "pizco", "planta", "playa", "plena", "pleno", "poblo", "pocas", "pocos", "podas",
  "poded", "poder", "podes", "podra", "podre", "podais", "podia", "polos", "poned", "ponen", "poner", "pones",
  "ponga", "pones", "ponia", "porfa", "poros", "posas", "posee", "posen", "poses", "posos", "posas", "poses",
  "potos", "poyas", "pozos", "prada", "prado", "preve", "primo", "probo", "pueda", "puede", "puedo", "pujan",
  "pujas", "pujen", "pujas", "pulen", "pulsa", "pumas", "puras", "purga", "puros", "quede", "queme", "quemo",
  "quema", "queme", "quemo", "quepa", "quere", "quise", "quiso", "quito", "rabat", "rabeo", "rabia", "rabos",
  "rabon", "ralbe", "ralbe", "ramos", "ranas", "rapas", "raras", "raros", "rasas", "rasco", "rasca", "raspa",
  "ratas", "ratos", "razas", "raeis", "reces", "recia", "recio", "redes", "regia", "reina", "reino", "rejas",
  "remas", "remes", "remos", "remas", "remes", "renos", "rento", "renta", "rento", "reses", "reste", "resto",
  "retes", "retos", "retes", "reyes", "rezan", "rezas", "reios", "reuna", "rices", "rifas", "rimas", "rimen",
  "rimes", "rimas", "rimes", "rinda", "ritos", "roban", "robes", "rocas", "rodas", "rojas", "rojos", "roles",
  "rolla", "rollo", "romas", "romos", "rompa", "rompe", "rompe", "rondo", "rones", "rotas", "rotos", "rotas",
  "royas", "royos", "royas", "rubis", "rucia", "rudos", "rueis", "rugen", "ruges", "rugio", "rugis", "rujan",
  "rulos", "runas", "rusas", "rusia", "rusos", "rutas", "rueis", "runas", "runas", "sabia", "sacan", "sacas",
  "sacos", "sacra", "sacas", "sajon", "sakes", "saldo", "salga", "salgo", "salta", "salta", "salto", "salud",
  "salva", "salve", "salvo", "salis", "samoa", "sanad", "sanas", "sanos", "santa", "sapos", "sarda", "saudi",
  "sebos", "secan", "secas", "sedad", "sedan", "sedas", "seden", "sedes", "sella", "senta", "sente", "sento",
  "sepas", "seres", "seria", "serro", "seran", "seras", "setas", "setos", "sexos", "siega", "sigan", "siria",
  "siseo", "situó", "soban", "sobas", "sobes", "sobre", "sodas", "sogas", "solas", "soles", "solos", "solia",
  "somos", "sonad", "sonar", "sonda", "sonas", "soplo", "sopas", "sorbe", "sorda", "sones", "subas", "subes",
  "sucia", "sucre", "sudan", "sudar", "sudes", "suda", "suela", "suele", "suena", "suene", "sueno", "suiza",
  "sumas", "supon", "suras", "sushi", "super", "tabas", "tabus", "tacos", "talas", "tales", "tapas", "tapen",
  "tarda", "tarde", "tegus", "tejas", "telas", "temas", "temen", "temes", "tened", "tenga", "tengo", "tenia",
  "tensa", "tenes", "terca", "tersa", "terso", "testo", "testa", "tetar", "tetas", "texas", "tiene", "times",
  "tipos", "tiras", "tiros", "tisus", "titan", "tocas", "todas", "todos", "togas", "tomad", "toman", "tomas",
  "tomes", "tonga", "tonos", "tonta", "topas", "topos", "toque", "torpe", "tosed", "toses", "traed", "traen",
  "traer", "traes", "traga", "trajo", "trama", "trato", "traia", "trine", "trino", "troco", "trono", "troto",
  "trios", "tubos", "tulio", "tumba", "tunas", "tolar", "tunez", "ubres", "untes", "unias", "urbes", "urdas",
  "uribe", "urnas", "usaos", "usate", "useis", "vacan", "vacas", "vados", "vagas", "vagos", "vague", "vage",
  "vamos", "vanos", "vasca", "vasos", "vasta", "vates", "vayan", "vayas", "veces", "vedas", "velas", "velen",
  "veles", "velos", "vemos", "venas", "vende", "vengo", "vente", "verde", "veros", "veras", "vereis", "veria",
  "vetas", "vetos", "veian", "veias", "viaje", "vidas", "viera", "vigas", "viles", "vinos", "vires", "visco",
  "viste", "vivas", "voces", "volar", "volvi", "volas", "votad", "votan", "votar", "votas", "voten", "votes",
  "votos", "votas", "votes", "vudus", "video", "wikis", "wones", "yates", "yemas", "yemen", "yendo", "yenes",
  "yesca", "yogur", "yugos", "zacas", "zarca", "zares", "zedas", "zetas", "zonas", "zorro", "zulus", "zurda",
  "zurro", "acida", "acido", "acima", "acimo", "afila", "afilo", "ambar", "anima", "apoda", "apodo", "arabe",
  "arbol", "arida", "arido", "asate", "atica", "atico", "atomo", "atona", "atono", "aurea", "aureo", "avara",
  "avaro", "avida", "avido", "ebola", "emula", "emulo", "epale", "epica", "epico", "epoca", "etica", "etico",
  "exito", "icono", "ignea", "igneo", "obolo", "ocre", "ohmica", "ohmico", "opera", "opimo", "orale", "oseas",
  "oseos", "otica", "otico", "ovida", "ovido", "ovolo", "ujule", "unica", "unico", "urica", "urico", "usate",
  "usese"
];